int msgid;
struct scheduler sch;
int finishedProcesses;
struct PCB* pcb;
int recievedProcesses;
int totalProcesses;
int finishedProcesses;
struct Process* runningProcess;
struct Process* newProcess;
int totalWaitingTime;
int totalWTA;

//Functions definition
void initializeScheduler();
void handlerINT(int);
bool checkNewProcesses(void* container);
void pushIntoConatainer(void*,int,struct Process*);
void startProcess(struct Process*);
void insertPCBSlot(struct PCB*,struct Process*,pid_t);
struct Process* getProcessByID(pid_t);
void stopProcess(struct Process*);
void continueProcess(struct Process*);
void updateOutfile(struct Process*, enum processState);
pid_t getProcessID(struct Process*);
void updatePCB(struct PCB *,struct Process*,enum processState);
void finishProcessHandler(int);
void generateLogFile();
void SRTN_Algo();
void HPF_Algo();
void RR_Algo(char*);