//Scheduler data members
int msgid;
pcb_t* pcb;
process_t* runningProcess;
process_t* lastRecieved;
int Algo;
int timeSlice;
int finishedProcesses;
int recievedProcesses;
int totalProcesses;
int totalWT;
int totalRT;
float totalWTAT;

//Functions definition
void initializeScheduler();
void handlerINT(int);
bool checkNewProcesses(void*);
void pushIntoConatainer(void*,int,process_t*);
void startProcess(process_t*);
void insertPCBSlot(pcb_t*,process_t*,pid_t);             
process_t* getProcessByID(pid_t);
void stopProcess(process_t*);
void continueProcess(process_t*);
void updateOutfile(process_t*);
pid_t getProcessID(process_t*);
void updatePCB(pcb_t*,process_t*,state_t);    
void finishProcessHandler(int);
void generatePrefFile();
void SRTN_Algo();
void HPF_Algo();
void RR_Algo(char*);
void destroyPCB();